### ISSUE TITLE
gitCheckout add noTags

### ISSUE THREAD

**Issue by tarekziade** [elastic/apm-pipeline-library#1024]
gitCheckout forces `noTags` to false. It would be great if we could surface that option.

happy to write a patch

**Comment by v1v** [comment]
I just kicked off a new release -> https://apm-ci.elastic.co/job/apm-shared/job/apm-pipeline-library-mbp/job/master/1455/

https://github.com/elastic/apm-pipeline-library/releases/tag/v1.1.198 will be available in 20 minutes or so

**Comment by tarekziade** [comment]
Thanks @v1v
