### ISSUE TITLE
Investigate code coverage tools for the library

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1032]
Following discussion here: https://github.com/jenkinsci/JenkinsPipelineUnit/issues/103#issuecomment-596219941

**Comment by v1v** [comment]
https://github.com/elastic/apm-pipeline-library/pull/353 was the very first attempt but we discarded since we had to redesign the library

**Comment by mdelapenya** [comment]
Take a look at https://github.com/elastic/apm-pipeline-library/compare/master...mdelapenya:code-coverage?expand=1#diff-2171808c71d9548ad291136c0fdcc8f9520b579a51b629b11f6817b770427bd7R18 and https://github.com/elastic/apm-pipeline-library/compare/master...mdelapenya:code-coverage?expand=1#diff-e7eb79788ad50a741c5351c822b568542505804d07053f497218842b74b18313R27

Although redundant in the sense it keeps both files (the `vars/a.groovy` and the `src/co/elastic/vars/a.groovy`), the layout of the library would not be affected, but the logic will be moved to the SRC dir, which could ideally, simplify the usage of the existing tooling in Maven world.

**Comment by mdelapenya** [comment]
I think this can be closed for now
