### ISSUE TITLE
Rethink how to present the documentation for the steps (and maybe more)

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1044]
The vars/README.md file is huge, and it would be great to have a better manner to present the docs for each step, and maybe the library in general. I can picture using something like a static site CMS project like Jekyll, HugoCMS (and more), or [readthedocs](https://docs.readthedocs.io/en/stable/index.html) could help.

**Comment by mdelapenya** [comment]
Related to the ONWeek project and backstrage. cc/ @cachedout

**Comment by kuisathaverat** [comment]
The txt files are in the format accepted by Jenkins.
