### ISSUE TITLE
filebeat and metricbeat steps are not working on ARM

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1072]
When using filebeat on ARM, we get this error:

>[2021-04-08T23:19:42.432Z] WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Same for metricbeat step

**Comment by v1v** [comment]
We won't invest anymore in the existing Jenkins implementation unless a security or a major bug, hence I'll close this issue now
