### ISSUE TITLE
Add GOARCH to withGoEnv step

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1121]
@v1v do you think we can revert 0cd42e05badadaaa9e88c37ae4638033dcd3c8ff and apply that change to https://github.com/elastic/apm-pipeline-library/blob/6cfa9fac78ca050023ac0b5aa55de8d4090ff41c/vars/withGoEnvUnix.groovy#L48? Therefore, we will be setting the proper GOARCH value across any build.

_Originally posted by @mdelapenya in https://github.com/elastic/e2e-testing/pull/707#r589276064_

**Comment by v1v** [comment]
I don't understand your question :/

What does the commit `0cd42e05badadaaa9e88c37ae4638033dcd3c8ff` refer to?

The `GOARCH` is configured in the contest of the installing the packages:

https://github.com/elastic/apm-pipeline-library/blob/b9cc99960eddbe64f85ea93715255b64247ea39a/vars/withGoEnvUnix.groovy#L67-L73

Do you think if moving that section to the L48 would be sufficient? I guess it should not cause any issues on the other hand.

**Comment by v1v** [comment]
Aha, the comment in https://github.com/elastic/e2e-testing/pull/707/files#r589276064 :)
