### ISSUE TITLE
"googleStorageUploadExt" step should check if there are no matched files in the pattern

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1169]
If that file does not exist, then `gsutil` fails

i.e.:

>[2021-06-16T14:56:28.509Z] + gsutil -m -q cp -a public-read build/system-tests-*.tar.gz gs://beats-ci-temp/Beats/beats/PR-26209-11
[2021-06-16T14:56:29.451Z] CommandException: No URLs matched: build/system-tests-*.tar.gz
[2021-06-16T14:56:31.359Z] CommandException: 1 file/object could not be transferred.
script returned exit code 1

**Comment by v1v** [comment]
What do you want to this in this particular case? Patterns can be complex, so I'd rather prefer to keep the failure coming from `gsutil`

**Comment by mdelapenya** [comment]
Yeah, I was thinking about that step at first instance too. I'd like to simply log that there are no matching files, and to skip the upload. This corner case has been found here: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-26209/11/pipeline/1245/, where the `args.upload` for the Beats seems to be true but there are not generated files to upload.

**Comment by v1v** [comment]
I managed to find that we cannot use wildcards at the beginning of the pattern
