### ISSUE TITLE
No signature of method: java.lang.Boolean.trim() in doNotifyBuildResult

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-pipeline-library#1175]
We are trying to make a trim of a boolean in the doNotifyBuildResult step

![image](https://user-images.githubusercontent.com/5400788/123225639-32c6a800-d4d3-11eb-9bc8-35e9d562b555.png)

```
08:00:14  hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: java.lang.Boolean.trim() is applicable for argument types: () values: []
08:00:14  Possible solutions: wait(), grep(), wait(long), print(java.io.PrintWriter), is(java.lang.Object), print(java.lang.Object)
08:00:14  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:154)
08:00:14  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
08:00:14  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
08:00:14  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
08:00:14  	at WorkflowScript.run(WorkflowScript)
08:00:14  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:431)
```

**Comment by kuisathaverat** [comment]
that red X is to indicate that the email that we will send is for a FAILURE so the mail stage did not failed, it failed loading the template.

**Comment by kuisathaverat** [comment]
no, it is failling on the initialising of the environment

**Comment by kuisathaverat** [comment]
We have winner:

![image](https://user-images.githubusercontent.com/5400788/123260069-76320e00-d4f5-11eb-8238-f5483a6877a7.png)

and then we make `BEAT_VERSION = "${params.BEAT_VERSION.trim()}"` that failed because BEAT_VERSION is a Boolean.

**Comment by mdelapenya** [comment]
The root cause analysis drove us to realise the caller build, Beats, was defining the BEAT_VERSION as a boolean, which is totally wrong. Thanks @kuisathaverat for the investigation. We found it in https://github.com/elastic/beats/pull/26291/files#diff-5edb5ab93fc95960129eecb2ee3d8763a9c5e02b56e5b80126e0c5a52296ee8fR435
