### ISSUE TITLE
`retryValue` never used in `gitCheckout`

### ISSUE THREAD

**Issue by tarekziade** [elastic/apm-pipeline-library#1205]
We don't use the `retryValue` https://github.com/elastic/apm-pipeline-library/blob/master/vars/gitCheckout.groovy#L43

I assume we want to plug it in a `retryWithSleep` call ?

**Comment by v1v** [comment]
Initial implementation done in https://github.com/elastic/apm-pipeline-library/pull/306

And it looks like it's a leftover from https://github.com/elastic/apm-pipeline-library/pull/352


We can safety removed, thanks for the finding this :)
