### ISSUE TITLE
coverageReport: support setting the coverage file by parameter

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1240]
It's now hardcoded to `coverage-*-report.xml` (See https://github.com/elastic/apm-pipeline-library/blob/f460c26aea47055f07550cc56ae9e16572f9fe2d/vars/coverageReport.groovy#L41)

I'd see it convenient to make the report file (maybe without the extension) configurable by parameter.

What I see is that the current implementation expects a simple string, and we'd need a Map. Not sure if changing the signature will be backwards compatibility, breaking consumers of the `coverageReport` step.

**Comment by v1v** [comment]
We won't invest anymore in the existing Jenkins implementation unless a security or a major bug, hence I'll close this issue now
