### ISSUE TITLE
Slack notification for pipelines: the link to the APM traces should be customizable

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1247]
In the use case of the e2e-testing framework, apart from the APM traces for the CI itself, we contribute APM traces for the tests themselves.

As a consumer of the slack notification, I'd like to be able to follow two APM links: one for the CI one for the tests, as they now live in two separated clusters (which makes me think if we should send the test traces to the same ES cluster)

**Comment by v1v** [comment]
There are two different approaches here but in a nutshell, the e2e-testing might need to use the env variables:

* `OTEL_EXPORTER_OTLP_ENDPOINT`
* `OTEL_EXPORTER_OTLP_HEADERS`

if there are set.

Those env variables can be potentially exposed implicitly by the Jenkins OTEL plugin itself (see https://github.com/jenkinsci/opentelemetry-plugin/commit/021085f51d4bf06cc4c3b7141e963387fdee1d62) or the shared library could provide them (see https://github.com/elastic/apm-pipeline-library/blob/master/vars/withOtelEnv.txt and https://github.com/elastic/apm-pipeline-library/pull/1234 ), for the latter it's required to change the pipeline to use the step `withOtelEnv`

In any case, it's required to change the e2e-testing accordingly to consume those env variables if they are set.

Do you think that could be sufficient?

**Comment by mdelapenya** [comment]
I think #1250 will resolve this question. Closing!
