### ISSUE TITLE
[dockerLogin] Support passing env vars to the closure

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1305]
My use case needs the docker credentials to access the private docker registry to be set in the execution, and for that we would need to create a way to pass the DOCKER_USER and DOCKER_PASSWORD:

```golang
	authConfig := types.AuthConfig{
		Username: os.Getenv("DOCKER_USER"),
		Password: os.Getenv("DOCKER_PASSWORD"),
	}
	encodedJSON, err := json.Marshal(authConfig)
	if err != nil {
		return err
	}


	options := types.ImagePullOptions{
		Platform:     platform,
		RegistryAuth: base64.URLEncoding.EncodeToString(encodedJSON),
	}
	c.ImagePull(ctx, "docker.elastic.co/observability-ci/kibana:pr123456", options)
```

I'd suggest having a `withDockerLogin` step, which wraps the closure adding those env vars

**Comment by v1v** [comment]
I'd say the step name = `withDockerEnv`. The main reason: `withOtelEnv` or `withMageEnv`, `withCloudEnv` or `withAzureEnv` are some other steps that provide the environmental context to run in the given closure.
