### ISSUE TITLE
New step: check that the git state is not modified

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#1339]
If we are running commands that could modify already committed files, we'd like to prevent the build to continue in the case those file were modified, meaning somebody forgot to commit them.

An example could be:

```
withGitStatusCheck() {
    body()
}
```

If body modifies the git state (== there are modified and not committed files after the execution of body), then fail.

I guess it should work in both Nix and Windows, as the command `git diff --staged --quiet` should be cross-platform. We must take care of the exit code in both OSs to fail the step in consequence

**Comment by v1v** [comment]
We won't invest anymore in the existing Jenkins implementation unless a security or a major bug, hence I'll close this issue now
