### ISSUE TITLE
Add "packageStoragePublish" function

### ISSUE THREAD

**Issue by mtojek** [elastic/apm-pipeline-library#1606]
Follow-up: https://github.com/elastic/elastic-package/pull/728/

The goal of this issue is to support package publishing to the new Package Storage v2. I suggest the following design:

Function name: **packageStoragePublish**
Input parameters: 
* **buildPackagesPath** - path to the directory with .zip files
* _map_ containing all required credentials, secrets, work dirs, etc.

Actions:
1. Identify packages not published to the Package Storage.
2. Sign unpublished packages using the Elastic signing pipeline.
3. Publish packages and signatures using [publishing job](https://internal-ci.elastic.co/job/package_storage/job/publishing-job-remote/)

In general, we have already implemented all these steps [here](https://github.com/elastic/elastic-package/blob/main/.ci/package-storage-publish.groovy). We need to move it to this repository.

Dear Robots, I think we can handle this on our own and ask you later for review.

**Comment by v1v** [comment]
We are moving to GH actions so no need work on this now
