### ISSUE TITLE
[pytest-otel] `from _pytest import timing` may fail

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-pipeline-library#1622]
On this line https://github.com/elastic/apm-pipeline-library/blob/9d3c9d0796e22cb45090597aeeadf8a9a1ccdfb0/resources/scripts/pytest_otel/src/pytest_otel/__init__.py#L11

a module is imported that has been added to pytest in 6.0 (see https://github.com/pytest-dev/pytest/commit/1780924b279a80aa3cccd840229dfe3e6f60e88b).

Meanwhile, `install_requires` still says `pytest>5`:

https://github.com/elastic/apm-pipeline-library/blob/9d3c9d0796e22cb45090597aeeadf8a9a1ccdfb0/resources/scripts/pytest_otel/setup.cfg#L39

The `timing` module doesn't seem to get used further down, so removing it might also be an option instead of bumping the required version of pytest

**Comment by kuisathaverat** [comment]
I will remove it, IIRC is a leftover of a workaround to run pytest inside pytest as a subprocess and I do not use the workaround anymore
