### ISSUE TITLE
AttributeError: 'Function' object has no attribute '_store'

### ISSUE THREAD

**Issue by 1Mark** [elastic/apm-pipeline-library#1839]
If assertion fails, pytest_runtest_call raises an exception here  at line 334 https://github.com/elastic/apm-pipeline-library/blob/1ecde6cf3745c6889ab09b55e9d442d474897c07/resources/scripts/pytest_otel/src/pytest_otel/__init__.py#L331-L337

 ```python
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

item = <Function test_otel_spans>

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_call(item):
        global outcome, session_name, spans
        with tracer.start_as_current_span(
            "Running {}".format(item.name),
            context=trace.set_span_in_context(spans[session_name]),
            record_exception=True,
            set_status_on_exception=True,
        ) as span:
            #total_counter.add(1)
            LOGGER.debug("Test {} starts - {}".format(item.name, span.get_span_context()))
            span.set_attribute("tests.name", item.name)
            yield
            LOGGER.debug("Test {} ends - {}".format(item.name, span.get_span_context()))
            breakpoint()

>           if hasattr(sys, "last_value") and hasattr(sys, "last_traceback") and hasattr(sys, "last_type"):
E           AttributeError: 'Function' object has no attribute '_store'

../.pyenv/versions/3.8.7/envs/.venv/lib/python3.8/site-packages/pytest_otel/__init__.py:301: AttributeError
```

test to reproduce the issue
```python
def test_otel_spans():
    assert [json.loads(span.to_json()) for span in otel_exporter.get_finished_spans()] == [{}]
```

**Comment by 1Mark** [comment]
The logic here for checking if a test is marked as skipped seems odd. Since `xfailed_key` is not a thing in `_pytest`.

**Comment by 1Mark** [comment]
https://github.com/pytest-dev/pytest/issues/7513#issue-660446510 I upgraded from pytest 5.3.2 to 7.1.2 the issue went away 🥳

**Comment by 1Mark** [comment]
Would be nice to add a restriction that you need pytest v6 or greater so this issue is fixed.

**Comment by v1v** [comment]
Thanks @1Mark for the debugging. Those requirements are set in:
- https://github.com/elastic/apm-pipeline-library/blob/dcbf2c4c6026925b905ec1bdfe4ba2ba7a9469e1/resources/scripts/pytest_otel/requirements.txt#L6
- https://github.com/elastic/apm-pipeline-library/blob/main/resources/scripts/pytest_otel/tox.ini#L11

I might need to figure out how to make them as hard-requirements, so others can benefit from

**Comment by 1Mark** [comment]
I think this should be set to 6?
