### ISSUE TITLE
pytest-otel - AttributeError: 'NoneType' object has no attribute 'get_current'

### ISSUE THREAD

**Issue by andrewkroh** [elastic/apm-pipeline-library#1969]
I was trying to perform a test with Auditbeat running on Ubuntu 22.04, but could not get pytest to run due to an otel related error. From https://github.com/elastic/apm-pipeline-library/issues/1687 it looks like we had overcome this error after upgrading opentelemetry-sdk dependencies, but perhaps something about Ubuntu 22.04 is different?

### Error

[Test run](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-33863/2/testReport/junit/x-pack.auditbeat.tests.system.test_exports/Test/Extended___x_pack_auditbeat_ubuntu_22_ubuntu_22___test_export_config/ )

```
platform linux -- Python 3.10.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
plugins: timeout-1.4.2, otel-1.1.1, rerunfailures-9.1.1
```

`AttributeError: 'NoneType' object has no attribute 'get_current'`

```
../../../../../../python-env/build/ve/linux/lib/python3.10/site-packages/pytest_otel/__init__.py:290: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../../../python-env/build/ve/linux/lib/python3.10/site-packages/opentelemetry/trace/propagation/__init__.py:34: in set_span_in_context
    ctx = set_value(_SPAN_KEY, span, context=context)
../../../../../../python-env/build/ve/linux/lib/python3.10/site-packages/opentelemetry/context/__init__.py:116: in set_value
    context = get_current()
../../../../../../python-env/build/ve/linux/lib/python3.10/site-packages/opentelemetry/context/__init__.py:67: in wrapper
    return func(*args, **kwargs)  # type: ignore[misc]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```

### Related things

- [Beat requirements.txt](https://github.com/elastic/beats/blob/c77b5e71caf6132db9eed6b7b6bc27a36270a00d/libbeat/tests/system/requirements.txt)
- https://github.com/elastic/beats/pull/33863
- https://github.com/open-telemetry/opentelemetry-python/issues/2288 
- https://github.com/elastic/apm-pipeline-library/issues/1687

**Comment by kuisathaverat** [comment]
Version 1.1.0 contains the fix for Python 3.10 issue, this version requires pytest 6.2.5, that's the issue in beats repo.
