### ISSUE TITLE
Fix failing docker images

### ISSUE THREAD

**Issue by reakaleek** [elastic/apm-pipeline-library#1992]
The migration of "build docker images" in https://github.com/elastic/apm-pipeline-library/pull/1986 revealed that some images are broken. Some have been removed because they are deprecated, but for some images it's still unclear.

This is a follow-up issue to clarify if those images need to be fixed or can be removed:

- [x] [azure-vm-tools](https://github.com/elastic/apm-pipeline-library/blob/0b145931c85b3d7aad481f76d398081f1fbb3cfa/.ci/.docker-images.yml#L46-L50)
  - https://github.com/elastic/apm-pipeline-library/pull/2013
- [x] [test-plans](https://github.com/elastic/apm-pipeline-library/blob/0b145931c85b3d7aad481f76d398081f1fbb3cfa/.ci/.docker-images.yml#L60-L66)
  - https://github.com/elastic/observability-robots/pull/1519
  - https://github.com/elastic/apm-pipeline-library/pull/2014
- [x] [kibana-yarn](https://github.com/elastic/apm-pipeline-library/blob/0b145931c85b3d7aad481f76d398081f1fbb3cfa/.ci/.docker-images.yml#L193-L198) https://github.com/elastic/apm-pipeline-library/pull/2021
- [x] [kibana-devmode](https://github.com/elastic/apm-pipeline-library/blob/0b145931c85b3d7aad481f76d398081f1fbb3cfa/.ci/.docker-images.yml#L200-L205) https://github.com/elastic/apm-pipeline-library/pull/2021
- [x] shellcheck (no clue how to fix)
- [x] [apm-integration-testing-all](https://github.com/elastic/apm-pipeline-library/blob/0b145931c85b3d7aad481f76d398081f1fbb3cfa/.ci/.docker-images.yml#L116-L121) (no clue how to fix)

**Comment by reakaleek** [comment]
I couldn't find a quick fix for shellcheck and apm-integration-testing-all. On hold in favour of pipeline migration.

**Comment by v1v** [comment]
I'll look at those failures this upcoming week and see what I can find, sorry for my late reply

**Comment by v1v** [comment]
https://github.com/elastic/apm-pipeline-library/pull/2062 is the one for the `shellcheck`

**Comment by v1v** [comment]
I'm able to reproduce the failures for the one for the `apm-integration-testing-all` 

```
make -C docker all-tests
```


```
1..5
not ok 1 apm-server - build image
# (from function `assert_success' in file tests/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file tests/tests.bats, line 18)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (474 lines):
#   #1 [internal] load build definition from Dockerfile
#   #1 sha256:f54e41427d6b145473ea15cfea6c49fea20a3580ece3c4b3fdcb99b81ed59f18
#   #1 transferring dockerfile: 2.09kB done
#   #1 DONE 0.0s
#   
```

```
#   #14 35.51 note: module requires Go 1.19
#   #14 42.24 # github.com/elastic/elastic-package/internal/kibana
#   #14 42.24 /go/pkg/mod/github.com/elastic/elastic-package@v0.72.0/internal/kibana/client.go:111:12: base.JoinPath undefined (type *url.URL has no field or method JoinPath)
#   #14 42.24 note: module requires Go 1.19
#   #14 73.02 make: *** [go.mk:43: /go/src/github.com/elastic/apm-server/build/linux/elastic-package] Error 2
#   #14 73.02 make: Leaving directory '/go/src/github.com/elastic/apm-server'
#   #14 ERROR: executor failed running [/bin/sh -c make -C ${SRC} update ${apm_server_binary} 	  && sed -zri -e 's/output.elasticsearch:(\n[^\n]*){5}/output.elasticsearch:\n  hosts: ["\${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]/' -e 's/  host: "localhost:8200"/  host: "0.0.0.0:8200"/' ${SRC}/apm-server.yml 	  && chmod go+r ${SRC}/apm-server.yml]: exit code: 2
#   ------
#    > [build 7/7] RUN make -C /go/src/github.com/elastic/apm-server update apm-server 	  && sed -zri -e 's/output.elasticsearch:(\n[^\n]*){5}/output.elasticsearch:\n  hosts: ["\${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]/' -e 's/  host: "localhost:8200"/  host: "0.0.0.0:8200"/' /go/src/github.com/elastic/apm-server/apm-server.yml 	  && chmod go+r /go/src/github.com/elastic/apm-server/apm-server.yml:
#   ------
#   executor failed running [/bin/sh -c make -C ${SRC} update ${apm_server_binary} 	  && sed -zri -e 's/output.elasticsearch:(\n[^\n]*){5}/output.elasticsearch:\n  hosts: ["\${ELASTICSEARCH_HOSTS:elasticsearch:9200}"]/' -e 's/  host: "localhost:8200"/  host: "0.0.0.0:8200"/' ${SRC}/apm-server.yml 	  && chmod go+r ${SRC}/apm-server.yml]: exit code: 2
# --
# 

```


Though I might need to dive into this a bit more

**Comment by v1v** [comment]
I've just triggered https://github.com/elastic/apm-pipeline-library/actions/workflows/publish-docker-images.yml

Let's see if it works

**Comment by reakaleek** [comment]
Thank for the help @v1v!
