### ISSUE TITLE
Move to phoenix-actions/test-reporting

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/apm-pipeline-library#2063]
I [hit an issue](https://github.com/elastic/apm-pipeline-library/blob/1f521133d4f90c0ddb29571cd434fdfd3c44dca7/.github/actions/test-report/action.yml#LL63C13-L63C32) with setting `only-failed` for `test-suites` and `list-tests` where the documented `only-failed` does not parse correctly.

The documentation of `dorny/test-reporter` seems off here and it should be `failed`:

https://github.com/dorny/test-reporter/blob/e9fa2f582c0ebbe2e263fd18fad744d52e0b0203/src/main.ts#L39

However digging further it appears that this option is broken alltogether:

https://github.com/dorny/test-reporter/issues/142

https://github.com/phoenix-actions/test-reporting is a fork of `dorny/test-reporter` that appears to be more actively maintained. 

It might make sense to switch to this instead?

**Comment by v1v** [comment]
This is now done

Thanks for highlighting this
