### ISSUE TITLE
mvnVersion returns extra output from maven command

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-pipeline-library#2186]
The `mvnVersion` ([code](https://github.com/elastic/apm-pipeline-library/blob/5498f2a8c2e338214442a4684772246cfc5e21cf/vars/mvnVersion.groovy#L21)) method invokes the mvn wrapper to retrieve the current project version. 

With recent versions of maven, almost every invocation of `mvn` will start with some extra lines before the expected result:
```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /home/sylvain/.m2/wrapper/dists/apache-maven-3.8.5-bin/5i5jha092a3i37g0paqnfr15e0/apache-maven-3.8.5
Java version: 17-ea, vendor: Oracle Corporation, runtime: /home/sylvain/.sdkman/candidates/java/17.ea.33-open
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-52-generic", arch: "amd64", family: "unix"
1.37.1-SNAPSHOT
```

Here the expected result is `1.37.1-SNAPSHOT` to get the maven project version.

This comes from maven, not the wrapper itself, and I haven't found any option to disable this.
So maybe the best option for this `mvnVersion` method would be to only consider the last line of the output as the project version.

**Comment by v1v** [comment]
I think the issue is related to:
- https://github.com/elastic/apm-agent-java/blob/main/.mvn/maven.config

if I delete it then

```
➜   ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /Users/vmartinez/.m2/wrapper/dists/apache-maven-3.8.5-bin/5i5jha092a3i37g0paqnfr15e0/apache-maven-3.8.5
Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /Users/vmartinez/.sdkman/candidates/java/17.0.5-tem
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.3", arch: "x86_64", family: "mac"
1.36.1-SNAPSHOT%                                                                                                                                                                                                                                                                                           ➜  mv .mvn/maven.config .mvn/maven.configbck
➜  ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout
1.36.1-SNAPSHOT%  
```

**Comment by v1v** [comment]
https://github.com/elastic/apm-pipeline-library/pull/2196 is the proposal
