### ISSUE TITLE
Slack message: step failures message could be misleading

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#790]
The below message represents a green build with 0 failed tests, but it shows a Steps failures block with value 1, caused by a `dockerLogin` that failed but was retried.

<img width="376" alt="Screenshot 2020-10-23 at 08 41 36" src="https://user-images.githubusercontent.com/951580/96964909-94311400-150b-11eb-8fc4-5ab9c9d913db.png">

I wonder if this message could be enhanced in some way:

a. skip the step failures block if and only if the build is SUCCESS, or
b. rename the block to retried steps, or
c. any suggestion?

My main concern about it, from a consumer perspective, is on the value of presenting that information with such an importance.

**Comment by v1v** [comment]
We could skip the step failures block if things are fine, although it's good to know if something happened, so no strong opinions.
