### ISSUE TITLE
Github comment template always includes a badge for docs preview

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#796]
I'd see convenient to always skip this badge, unless set in the caller. Otherwise we will be posting a badge that links to nowhere:

This PR has nothing to do with docs previews:
<img width="929" alt="Screenshot 2020-10-28 at 04 25 55" src="https://user-images.githubusercontent.com/951580/97387146-ba70fe00-18d5-11eb-9fd2-49dad34b9c32.png">

<img width="582" alt="Screenshot 2020-10-28 at 04 25 16" src="https://user-images.githubusercontent.com/951580/97387105-9e6d5c80-18d5-11eb-8102-64832a75565c.png">

Thoughts?

**Comment by v1v** [comment]
I'm afraid there is no way to know dynamically when it should be enabled/disabled since the `elasticsearch-ci/docs` check is not managed by us, so it's configured by default to avoid some complexity when it should be shown or not

**Comment by mdelapenya** [comment]
Although interesting, I think this can be closed for now
