### ISSUE TITLE
GitHub comments aggregation

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#834]
@beniwohli pointed that the current flaky test comments in GitHub is noisy in some scenarios.

The main reason to notify always was to avoid the feeling that when no notifications then things are fine but there is a potential issue that the notifications failed for some other reasons.

As a way to workaround it we could aggregate both comments with just one comment with two sections. 

#### With two comments

![image](https://user-images.githubusercontent.com/2871786/98684013-9691cb80-235d-11eb-9313-0e97159e8b97.png)

#### With one comment and two sections

![image](https://user-images.githubusercontent.com/2871786/98684084-ad382280-235d-11eb-8f68-e2bae57d7181.png)

**Comment by mdelapenya** [comment]
I like the second option!! I've also thought about the need of an empty flakiness comment, and this will address these concerns.

Thanks for raising the issue!
