### ISSUE TITLE
possible to use a "current" *branch* rather than tag?

### ISSUE THREAD

**Issue by trentm** [elastic/apm-pipeline-library#905]
https://github.com/elastic/apm-pipeline-library#manual-release-process-man-replaced-by-the-automated-process-above docs a process of *force* pushing the "current" tag. That leads to a need to use "force" options when fetching tags into a local git clone:

```
% git fetch --tags origin
From github.com:elastic/apm-pipeline-library
 ! [rejected]        current    -> current  (would clobber existing tag)

% echo $?
1

% git fetch -f --tags origin
From github.com:elastic/apm-pipeline-library
 t [tag update]      current    -> current
```

I wonder if the use case for the "current" ref could be satisfied by using a "current" *branch* rather than a tag.

This likely affects few people, and I'm making myself special by using the "--tags" option to "git fetch" in my typical workflow. If it is the case that no one else is really affected by this, then this is definitely a **low** priority. Don't spend a lot of time on it. :)

**Comment by v1v** [comment]
Hi @trentm ,

Thanks for reaching out, I'd like to ask you if you can explain what you tried and the reason. I have not faced this particular issue in the past so I'd like to understand your use case.

On the other hand, the reason for using current and version tags is about deploying easily new versions to the observability consumers, there are about ~60 repositories consuming this library. 

The release is always backward compatible in our end, and we ensure that behaviour, so even if we use current that normally points to the latest release, we can easily rollback to a previous release if the latest got some kind of regression. By using a branch we will end up in a backport mess when we need to rollback changes and point to an old release if required, it does not happen often but there is a possibility. That's probably my main concern if we'd move to branches instead tags.

Thanks

**Comment by trentm** [comment]
Using tags for versions, e.g. "v1.1.176", definitely makes sense to me. No argument there.

The "issue" I'm running into is only with the "current" *tag* because it changes over time. I'll try to describe how that affects my use case. (Note that as I said earlier, if this only affects me and not others, I can work around it just fine.)

If I clone this repo currently, I will get the "current" tag showing the recent update to commit 8ef7113ea954c8d30e3eacac47c5b9985f1cc306:

```
~/tmp % git clone git@github.com:elastic/apm-pipeline-library.git
Cloning into 'apm-pipeline-library'...
...
~/tmp % cd apm-pipeline-library
~/tmp/apm-pipeline-library % git log -1 current
commit 8ef7113ea954c8d30e3eacac47c5b9985f1cc306 (HEAD -> master, tag: current, origin/master, origin/HEAD)
Author: apmmachine <infra-root-apmmachine@elastic.co>
Date:   2021-01-15T08:49:40+00:00 (8 hours ago)

    docs: update CHANGELOG.md
```

However, if one had a clone from earlier (e.g. from before today) and attempt to update it via `git pull --rebase origin` or `git fetch origin` or similar, then I do **not** get the updated "current" tag:

```
~/el/apm-pipeline-library.bak % git pull --rebase origin
Updating b11b757..8ef7113
Fast-forward
...

~/el/apm-pipeline-library.bak % git log -1 current
commit 1405b404792fb9f8df6252e2e64826b468023313 (tag: current)
Author: apmmachine <infra-root-apmmachine@elastic.co>
Date:   2020-11-17T08:44:55+00:00 (8 weeks ago)

    docs: update CHANGELOG.md
```

To have a local clone match the tags and branches that the remote actually has I have, over time, evolved this alias for updating my local clones:

```
alias giddyup='git fetch --tags --prune --prune-tags -a origin && git pull --rebase origin $(git rev-parse --abbrev-ref HEAD) && git submodule update --init'
```

That is a mouthful and I fully admit that it gets into the realm of git voodoo.

When trying to write this answer, I noticed from https://stackoverflow.com/a/55268620 that as of git version 2.20 there was a change in behaviour around `git fetch`ing of tags and when `--force` is required. From <https://git-scm.com/docs/git-fetch>:

```
Until Git version 2.20, and unlike when pushing with git-push[1], any updates to refs/tags/* would be accepted without + in the refspec (or --force). When fetching, we promiscuously considered all tag updates from a remote to be forced fetches. Since Git version 2.20, fetching to update refs/tags/* works the same way as when pushing. I.e. any updates will be rejected without + in the refspec (or --force).
```

I think that I just need to adjust my usage pattern and switch to using `git fetch --tags --force` if and only if I care about having my local clone track *changing* tags.  I don't think my use case is worth adjusting how you use "current".  Cheers.

**Comment by v1v** [comment]
Hi @trentm ,

IIUC, this is regarding keeping up to date all the git repositories related to the observability team in your local machine, right? It's not something about running locally anything related to this project but keeping the git workspace healthy.

As I mention, I have not faced issues with tags that need to be forced, but for clarity let me explain that this particular project has been split in two different test scenarios:
- Unit testing, for such maven is the build system and does not to interact with the tags.
- Functional testing, there is no need to interact with the tags, since it mounts the current working directory as a volume in a jenkins docker container.

Thanks again for asking about this, but just wanna double check again with you if I missed something in this request regarding building/testing this project.

**Comment by trentm** [comment]
> this is regarding keeping up to date all the git repositories related to the observability team in your local machine, right? 

Correct.
