### ISSUE TITLE
GIT_BASE_COMMIT clarification/bug

### ISSUE THREAD

**Issue by andrewstucki** [elastic/apm-pipeline-library#927]
I'm not sure if this is expected behavior and the docs are just confusing, or if this is a bug.

According to the [github environment docs](https://github.com/elastic/apm-pipeline-library/blob/41ff35c343c20069e44d68b6ee790d1697ae2f4b/vars/README.md#githubenv) `GIT_BASE_COMMIT`:

> On PRs points to the commit before make the merge, on branches is the same as GIT_COMMIT and GIT_SHA

while doing a backport to a release branch `GIT_BASE_COMMIT` appears to have the commit of my forked repo rather than the base commit of the 7.11 branch that I want to merge into.

I was attempting to fix a broken 7.11 build due to a mismatch in go versions used between the 7.11 and master beats branches which resulted in a test that was trying to generate artifacts requiring go 1.15 with a go 1.14 installation (see the [attempted fix](https://github.com/elastic/beats/pull/23699/commits/a79127983bf0a6dc9c730cf8f645f0bda71bb60a) for more info).

That build failed with:

> [2021-01-26T22:49:34.423Z] go get github.com/elastic/beats/v7@a79127983bf0a6dc9c730cf8f645f0bda71bb60a: github.com/elastic/beats/v7@a79127983bf0a6dc9c730cf8f645f0bda71bb60a: invalid version: unknown revision a79127983bf0a6dc9c730cf8f645f0bda71bb60a
[2021-01-26T22:49:34.423Z] Error: running "go get -d -u github.com/elastic/beats/v7@a79127983bf0a6dc9c730cf8f645f0bda71bb60a" failed with exit code 1

due to `a79127983bf0a6dc9c730cf8f645f0bda71bb60a` being the SHA in my fork's branch rather than `3577861957e165db2412cb2d38326b1c62c15205` which was the SHA of the target branch.

So, as follow up:

1. If the behavior of is as designed, I think we need to clarify the wording of `GIT_BASE_COMMIT` and potentially look into adding an environment variable like `GIT_ORIGIN_BASE_COMMIT` or something of the sort which always points to the tip of the branch that is the target of the PR.
2. If the behavior is broken, we have ourselves a bug 😄 

cc: @elastic/observablt-robots

**Comment by v1v** [comment]
@andrewstucki, thanks for raising this issue.

As far as I see, `GIT_BASE_COMMIT` or any other env variables generated with the `githubEnv` step are not something to be used outside of the CI, they were created for some other reasons. 

In my opinion, https://github.com/elastic/beats/pull/23699/commits/a79127983bf0a6dc9c730cf8f645f0bda71bb60a should not use that particular environment variable but using another approach. Otherwise, there is dependency of the project with this library, while it should be CI agnostic.

Those are my thoughts, happy to jump to a call to help with

**Comment by kuisathaverat** [comment]
`GIT_BASE_COMMIT` contains the latest real commit on your PR/Branch, what it means? you have a PR with the SHA `A`, `B`, and `C`, then the CI makes a merge with the `CHANGE_TAGET`, this new commit is  `D`, at this point GIT_COMMIT and GIT_SHA will have the value `D`.  This `D` value is not a real commit on the repo (any repo), for some operation we need a real commit so we implemented a login to grab the `C` commit in the variable `GIT_BASE_COMMIT`. `C` is in the repo but in the refspec: 'refs/pull/*/head'.

to make `go get` to work with those commit you need to add the refspec: '+refs/heads/*:refs/remotes/origin/* +refs/pull/*/head:refs/remotes/origin/PR/*' to your git configuration.

**Comment by kuisathaverat** [comment]
Could you explain a little what you want to achieve?

**Comment by andrewstucki** [comment]
@v1v -- I'm fine with doing a different approach -- it is slightly tricky because of the fact that in order for the `Makefile` to pick up the proper branch to use for the build dependency, it has to know what branch it should be targeting, but I think I can likely come up with a solution with parsing out the `stack_version` asciidoc entry from `libbeat/docs/version.asciidoc` -- similar to other places in the beats code base.

@kuisathaverat -- thanks for explaining, I'm thinking it might be helpful to update the description of that in the docs then to clarify that by:

> On PRs points to the commit before make the merge

It means

> On PRs this points to the latest commit in the author's fork (prior to overlaying the changes on top of `CHANGE_TARGET`)

It sounds like what I likely wanted was to use `CHANGE_TARGET` -- the "make the merge" part is a bit ambiguous and I thought that it was referencing merging the PR itself so that it corresponded to the latest commit SHA in the target branch. That said, I'll see if maybe I can whip something together that is agnostic of environment variables, like @v1v suggested -- but think it would be helpful to clarify the docs.

**Comment by v1v** [comment]
We won't invest anymore in the existing Jenkins implementation unless a security or a major bug, hence I'll close this issue now
