### ISSUE TITLE
Filebeat: support not overriding the image

### ISSUE THREAD

**Issue by mdelapenya** [elastic/apm-pipeline-library#990]
As the functionality this step offers is very opinionated, I suggest not allowing a consumer of the step to replace the image. I'd probably want to change the filebeat version, not the image. Something like:

```groovy
filebeat(version: "7.11.0", ...)
```
instead of:
```groovy
filebeat(image: "docker.elastic.co/beats/filebeat:7.11.0", ...)
```

**Comment by kuisathaverat** [comment]
the `image` covers the case of different Docker images and different versions, the `version` parameter only covers the change of version. I think we should not remove the `image` parameter. We could add the `version` as a short way to set the Docker image.
