### ISSUE TITLE
[discuss] GitHub PR Comment to skip failed steps if SUCCESS

### ISSUE THREAD

**Issue by v1v** [elastic/apm-pipeline-library#991]
@kuisathaverat got a good point regarding the GitHub PR comment with failed steps when no failed tests and SUCCESS builds.

@elastic/observablt-robots, should we skip any references to any failed steps if the build was successful run in the CI?

**Comment by kuisathaverat** [comment]
the thing is if we want to report on those messages all the steps that we trap in a catch, this means the build will succeed because all those steps are expected that fails, an example is anything we put on a retry, catchError, ty{}, ...
